#!/usr/bin/env python3
"""
python3-randword

gets the definition of a random word
created by Connor Ruggles
"""

import json
import os
import random
import sys
import requests

API_KEY = "YOUR API KEY HERE"
BASE_URL = "http://api.wordnik.com:80/v4/word.json/"

def load_words(dirpath):
    try:
        filename = dirpath + "/words_alpha.txt"
        if not os.path.exists(filename):
            print("rand-word: cannot stat " + str(filename))
            sys.exit(1)
        with open(filename, "r") as dictionary:
            words = dictionary.readlines()
            words = [x.strip('\n') for x in words]
            return words
    except Exception as e:
        return str(e)

def get_def(word_list):
    num_word = random.randint(0, 370098)
    params = "/definitions?limit=200&api_key=" + API_KEY
    req = requests.get(BASE_URL + word_list[num_word] + params)
    if req.status_code == 200:
        return (word_list[num_word], json.loads(json.dumps(req.json())))
    else:
        print("error retrieving word; try again later")
        sys.exit(1)

def print_defs(defs):
    print(defs[0])
    i = 1
    for defin in defs[1]:
        print(str(i) + ". " + defin["text"])
        i += 1

def usage():
    print("usage: rand-word [path]")
    print("Options:")
    print("path : full path to the file \"words_alpha.txt\".")
    print("       Defaults to the directory where the script")
    print("       is located.")
    sys.exit(1)

if __name__ == "__main__":
    if len(sys.argv) > 2:
        usage()
    if len(sys.argv) > 1:
        if sys.argv[1] == "help":
            usage()
        path = sys.argv[1]
    else:
        path = "."
    english_words = load_words(path)
    if isinstance(english_words, str):
        print("Error: " + english_words)
        sys.exit(1)
    word_info = get_def(english_words)
    while len(word_info) <= 0:
        word_info = get_def(english_words)
    print_defs(word_info)
    sys.exit(0)
